version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    labels:
      - "dependencies"
    reviewers:
      - "100terres"
    schedule:
      interval: "daily"
